//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoTray.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaoTray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Configuration file is not valid
        ///Please re-login
        ///Error {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_CONFIG_NOT_VALID {
            get {
                return ResourceManager.GetString("ERROR_CONFIG_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot retrieve data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_FETCH_DATA {
            get {
                return ResourceManager.GetString("ERROR_FETCH_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to retrieve user information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_FETCH_USER_DATA {
            get {
                return ResourceManager.GetString("ERROR_FETCH_USER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data is null に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_NULL_DATA {
            get {
                return ResourceManager.GetString("ERROR_NULL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The daily Commission has not been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_ALERT_DAILY {
            get {
                return ResourceManager.GetString("NOTIFY_ALERT_DAILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily Commission have yet to be reported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_ALERT_DAILY_EXTRA_REWARD {
            get {
                return ResourceManager.GetString("NOTIFY_ALERT_DAILY_EXTRA_REWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We have not used up half of the weekly boss resin consumption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_ALERT_WEEKLY_BOSS {
            get {
                return ResourceManager.GetString("NOTIFY_ALERT_WEEKLY_BOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data acquisition failure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All expedition completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_EXPEDITION_COMPLETED {
            get {
                return ResourceManager.GetString("NOTIFY_EXPEDITION_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Currency will be fully restored with {0} remaining に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_HOME_COIN_RECOVERY {
            get {
                return ResourceManager.GetString("NOTIFY_HOME_COIN_RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login Success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_LOGIN_SUCCESSFUL {
            get {
                return ResourceManager.GetString("NOTIFY_LOGIN_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on the tray icon to view information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_LOGIN_SUCCESSFUL_DESC {
            get {
                return ResourceManager.GetString("NOTIFY_LOGIN_SUCCESSFUL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Resin will recover with {0} remaining に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_RESIN_RECOVERY {
            get {
                return ResourceManager.GetString("NOTIFY_RESIN_RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parametric Transformer available! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOTIFY_TRANSFORMER_AVAILABLE {
            get {
                return ResourceManager.GetString("NOTIFY_TRANSFORMER_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   available に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_AVAILABLE {
            get {
                return ResourceManager.GetString("STATUS_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   completion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_EXPEDITION_FINISHED {
            get {
                return ResourceManager.GetString("STATUS_EXPEDITION_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_EXPEDITION_ON_GOING {
            get {
                return ResourceManager.GetString("STATUS_EXPEDITION_ON_GOING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIME_DAY {
            get {
                return ResourceManager.GetString("TIME_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} hours {1} minutes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIME_ETA {
            get {
                return ResourceManager.GetString("TIME_ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hours. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIME_HOUR {
            get {
                return ResourceManager.GetString("TIME_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIME_MINUTE {
            get {
                return ResourceManager.GetString("TIME_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIME_TODAY {
            get {
                return ResourceManager.GetString("TIME_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tomorrow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIME_TOMORROW {
            get {
                return ResourceManager.GetString("TIME_TOMORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ACCOUNT_LEVEL {
            get {
                return ResourceManager.GetString("UI_ACCOUNT_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nickname に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ACCOUNT_NICK_NAME {
            get {
                return ResourceManager.GetString("UI_ACCOUNT_NICK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select an account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ACCOUNT_TITLE {
            get {
                return ResourceManager.GetString("UI_ACCOUNT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ACCOUNT_UID {
            get {
                return ResourceManager.GetString("UI_ACCOUNT_UID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_ACCOUNT_CHANGE {
            get {
                return ResourceManager.GetString("UI_CONFIG_ACCOUNT_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right click to change account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_ACCOUNT_CHANGE_TOOL_TIP {
            get {
                return ResourceManager.GetString("UI_CONFIG_ACCOUNT_CHANGE_TOOL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_CLOSE {
            get {
                return ResourceManager.GetString("UI_CONFIG_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily Notifications に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_DAILY_NOTIFY {
            get {
                return ResourceManager.GetString("UI_CONFIG_DAILY_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily Commission not completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_DAILY_NOTIFY_DAILY_MISSION {
            get {
                return ResourceManager.GetString("UI_CONFIG_DAILY_NOTIFY_DAILY_MISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification time (HH:MM) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_DAILY_NOTIFY_TIME {
            get {
                return ResourceManager.GetString("UI_CONFIG_DAILY_NOTIFY_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   incomplete week boss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_DAILY_NOTIFY_WEEKLY_BOSS {
            get {
                return ResourceManager.GetString("UI_CONFIG_DAILY_NOTIFY_WEEKLY_BOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_ENABLE {
            get {
                return ResourceManager.GetString("UI_CONFIG_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   notify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_NOTIFY {
            get {
                return ResourceManager.GetString("UI_CONFIG_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minute notify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_NOTIFY_TIME {
            get {
                return ResourceManager.GetString("UI_CONFIG_NOTIFY_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account currently logged in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_NOW_LOGIN {
            get {
                return ResourceManager.GetString("UI_CONFIG_NOW_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Resin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_RESIN {
            get {
                return ResourceManager.GetString("UI_CONFIG_RESIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_SAVE {
            get {
                return ResourceManager.GetString("UI_CONFIG_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TaoTray Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_TITLE {
            get {
                return ResourceManager.GetString("UI_CONFIG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update interval (HH:MM:SS) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CONFIG_UPDATE_CYCLE {
            get {
                return ResourceManager.GetString("UI_CONFIG_UPDATE_CYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ERROR {
            get {
                return ResourceManager.GetString("UI_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Until concentrated resin can be made に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_CONDENSED_RESIN_RECOVERY_TIME {
            get {
                return ResourceManager.GetString("UI_INFO_CONDENSED_RESIN_RECOVERY_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily Commission に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_DAILY {
            get {
                return ResourceManager.GetString("UI_INFO_DAILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expedition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_EXPEDITION {
            get {
                return ResourceManager.GetString("UI_INFO_EXPEDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm Currency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_HOME_COIN {
            get {
                return ResourceManager.GetString("UI_INFO_HOME_COIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recovery to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_HOME_COIN_RECOVERY {
            get {
                return ResourceManager.GetString("UI_INFO_HOME_COIN_RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last update: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_LAST_UPDATED {
            get {
                return ResourceManager.GetString("UI_INFO_LAST_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   real-time note に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_REAL_TIME_NOTE {
            get {
                return ResourceManager.GetString("UI_INFO_REAL_TIME_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replenishment completion time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_RESIN_RECOVERY_ETA {
            get {
                return ResourceManager.GetString("UI_INFO_RESIN_RECOVERY_ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up to replenishment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_RESIN_RECOVERY_TIME {
            get {
                return ResourceManager.GetString("UI_INFO_RESIN_RECOVERY_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parametric Transformer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_TRANSFORMER {
            get {
                return ResourceManager.GetString("UI_INFO_TRANSFORMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weekly boss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_INFO_WEEKLY_BOSS {
            get {
                return ResourceManager.GetString("UI_INFO_WEEKLY_BOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_LOGIN_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("UI_LOGIN_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_LOGIN_LOGIN {
            get {
                return ResourceManager.GetString("UI_LOGIN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please log in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_LOGIN_NOT_LOGGED_IN {
            get {
                return ResourceManager.GetString("UI_LOGIN_NOT_LOGGED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log in to HoyoLab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_LOGIN_TITLE {
            get {
                return ResourceManager.GetString("UI_LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_MENU_ITEM_CLOSE {
            get {
                return ResourceManager.GetString("UI_MENU_ITEM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_MENU_ITEM_EXIT {
            get {
                return ResourceManager.GetString("UI_MENU_ITEM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_MENU_ITEM_SETTINGS {
            get {
                return ResourceManager.GetString("UI_MENU_ITEM_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update your data now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_MENU_ITEM_UPDATE_DATA {
            get {
                return ResourceManager.GetString("UI_MENU_ITEM_UPDATE_DATA", resourceCulture);
            }
        }
    }
}
